### ISSUE TITLE
Official NextAuth custom provider 

### ISSUE THREAD

**Issue by pi0neerpat** [UseKeyp/usekeyp-docs#90]
Lets see about adding ourselves to the official list of NextAuth providers.  

- [ ] Add a new provider here https://github.com/nextauthjs/next-auth/tree/main/packages/next-auth/src/providers
- [ ] Update docs https://next-auth.js.org/configuration/providers/oauth#built-in-providers

**Comment by jahabeebs** [comment]
PR made here: https://github.com/nextauthjs/next-auth/pull/7811

**Comment by pi0neerpat** [comment]
Closing as complete on our end
